In [1]:
import numpy as np
import gym
import random

In [2]:
env = gym.make("FrozenLake8x8-v0")

In [3]:
action_size = env.nA
state_size = env.nS

In [4]:
print("Total Action {}".format(action_size))
print("Total State {}".format(state_size))

Total Action 4
Total State 64


In [5]:
qtable = np.zeros((state_size, action_size))

In [6]:
# hyper parameters
total_episodes = 200000
max_steps = 256
gamma = 0.95
alpha = 0.8 # learning rate

#exploration parameters
epsilon = 1
min_epsilon = 0.01
max_epsilon = 1.0
decay_rate = 0.00001

In [7]:
# Training Stage
rewards = []
for episode in range(total_episodes * 2):
    
    state = env.reset()
    total_reward = 0
    done = False
    
    for step in range(max_steps):
#         trade_off  = random.uniform(0, 1)
        
#         if trade_off > epsilon:
#             action = np.argmax(qtable[state, :])
#         else:
#             action = env.action_space.sample()
        action  = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        #print("{} # step {} : {}".format(episode, step, reward))
        qtable[state, action] = qtable[state, action] + alpha * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_reward += reward
        
        state = new_state
        
        if done == True:
            break
            
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_reward)
    #rint("{} # epsilon : {}".format(episode, epsilon))
    #rint(" ", trade_off > epsilon)

print("Score Over Time {}".format(sum(rewards)/ total_episodes))
print("Q table :")
print(qtable)

Score Over Time 0.003755
Q table :
[[3.14186509e-01 3.10456966e-01 3.23534375e-01 3.16196783e-01]
 [3.11615596e-01 3.19830824e-01 3.20317809e-01 3.13473267e-01]
 [3.38828152e-01 3.40126317e-01 3.62939125e-01 3.73655292e-01]
 [3.93154821e-01 3.97595583e-01 3.84931926e-01 4.02137638e-01]
 [3.98302654e-01 3.90333487e-01 4.07321553e-01 3.97205129e-01]
 [4.40673069e-01 4.41975186e-01 4.31136666e-01 4.41015608e-01]
 [4.67661121e-01 4.65155430e-01 4.30920090e-01 4.22785425e-01]
 [4.51139157e-01 4.46485095e-01 4.57470362e-01 4.37698428e-01]
 [3.08321769e-01 3.28043813e-01 3.23952839e-01 3.15247201e-01]
 [3.14816480e-01 3.19363484e-01 3.39814022e-01 3.12310627e-01]
 [3.51401657e-01 3.37044898e-01 3.69725568e-01 3.82906169e-01]
 [1.26152095e-02 4.07955949e-01 3.08949098e-01 3.85915904e-01]
 [4.14953354e-01 3.99505722e-01 4.02388719e-01 3.85247847e-01]
 [4.29086672e-01 4.63893951e-01 4.28927200e-01 4.34711463e-01]
 [4.71187358e-01 4.95149334e-01 4.92747924e-01 4.44562072e-01]
 [4.70943939e-01 4.9

In [8]:
for episode in range(total_episodes):
    
    state = env.reset()
    total_reward = 0
    done = False
    
    for step in range(max_steps * 2):
        
        action = np.argmax(qtable[state, :])
        
        new_state, reward, done, info = env.step(action)
        #print("{} # step {} : {}".format(episode, step, reward))
        qtable[state, action] = qtable[state, action] + alpha * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_reward += reward
        
        state = new_state
        
        if done == True:
            break
            
    rewards.append(total_reward)

print("Score Over Time {}".format(sum(rewards)/ total_episodes))
print("Q table :")
print(qtable)

Score Over Time 0.839105
Q table :
[[2.58987313e-03 2.65210679e-03 5.72269271e-02 2.65332853e-03]
 [2.76786871e-03 2.79481051e-03 5.60263343e-02 2.89183219e-03]
 [3.71062929e-03 3.78699465e-03 3.68086549e-02 3.58440482e-03]
 [5.67852502e-03 6.29233170e-02 5.41490274e-03 4.24035412e-03]
 [7.68206635e-03 7.84692420e-03 1.30849533e-01 7.90213376e-03]
 [8.34063958e-03 8.28846569e-03 2.44752131e-01 8.41341384e-03]
 [1.04580588e-02 1.04524049e-02 1.71100889e-01 1.03669786e-02]
 [1.06056581e-02 1.07982577e-02 2.23633417e-01 1.08573903e-02]
 [2.60287237e-03 2.40612288e-03 2.21266100e-03 2.64707020e-02]
 [2.50283597e-03 2.34966490e-03 2.67700248e-03 3.58389075e-02]
 [1.76331493e-03 3.12613942e-03 1.97996958e-03 7.59110262e-02]
 [1.04794474e-03 2.52216606e-03 2.27936411e-03 7.40618567e-02]
 [6.14372796e-03 6.15086869e-03 6.02227590e-03 1.08564865e-01]
 [7.48943251e-03 6.94231096e-03 7.61328134e-03 2.76775427e-01]
 [1.09763431e-02 1.09881722e-02 2.99870864e-01 1.13957606e-02]
 [1.25028926e-02 1.8

In [10]:
# Testing Stage

state = env.reset()
done = False

for step in range(max_steps):

    action = np.argmax(qtable[state, :])

    new_state, reward, done, info = env.step(action)
    
    
    if done == True:
        env.render()
        print("It has taken {} steps.".format(step + 1))
        break
    state = new_state
    
env.close()

  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
It has taken 124 steps.
